apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-service-monitor
  namespace: keda-knative
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - keda-knative
  selector:
    matchLabels:
      app: keda
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
